fix spacing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,16 +19,16 @@ jobs:
       contents: read
 
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version: '24.x'
-      - run: npm run setup
-      - run: npm run rpack
-      - uses: actions/upload-artifact@v4
-        with:
-          name: dpr-package
-          path: dist
+    - uses: actions/checkout@v4
+    - uses: actions/setup-node@v4
+      with:
+        node-version: '24.x'
+    - run: npm run setup
+    - run: npm run rpack
+    - uses: actions/upload-artifact@v4
+      with:
+        name: dpr-package
+        path: dist
 
   test:
     runs-on: ubuntu-latest
@@ -68,7 +68,7 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
-          node-version: '22.x'
+          node-version: '24.x'
       - run: npm run setup
 
       - name: Clone mi-ui
@@ -104,7 +104,6 @@ jobs:
       - name: mi-ui integration tests
         run: npm run int-test
         working-directory: ${{ github.workspace }}/../app
-
   integration_test:
     runs-on: ubuntu-latest
     needs: build
@@ -129,6 +128,41 @@ jobs:
           node-version: '24.x'
       - run: npm run setup
       - run: npm run package
+      - name: count number of screenshots for visual regression tests before running
+        id: count-screenshots-before
+        run: echo -n "screenshots_before=$(find src/dpr/components/_dashboards/visual-regression-tests -name \*.png | wc -l | tr -d '[:space:]')" >> "$GITHUB_OUTPUT"
+
+      - name: Run the visual regression tests for dashboards
+        run: |
+          npx playwright install --with-deps
+          npm run int-test-visual
+
+      - name: count number of screenshots for visual regression tests after running
+        id: count-screenshots-after
+        run: |
+          echo "screenshots before: ${{ steps.count-screenshots-before.outputs.screenshots_before }}"
+          screenshots_after=$(find src/dpr/components/_dashboards/visual-regression-tests -name \*.png | wc -l | tr -d '[:space:]')
+          echo "screenshots after: $screenshots_after"
+          screenshot_diff=$((${{ steps.count-screenshots-before.outputs.screenshots_before }}-$screenshots_after))
+          if [ $screenshot_diff -eq 0 ]; then exit 0; else exit 1; fi
+      - name: Package up screenshots
+        if: success() || failure()
+        run: |
+          mkdir screenshots
+          find src/dpr/components/_dashboards/visual-regression-tests -name \*.png -exec cp {} screenshots \;
+
+      - uses: actions/upload-artifact@v4
+        name: Create screenshots artifact
+        if: success() || failure()
+        with:
+          name: screenshots
+          path: screenshots
+
+      - name: Output success or failure
+        id: output
+        if: success() || failure()
+        run: if [[ ${{ steps.count-screenshots-after.outcome }} != "success" ]]; then echo 'Visual regression test screenshots number changed - new tests likely added!' && exit 1; else exit 0; fi
+
       - name: Run the node app and integration tests
         id: int-test-step
         run: |
@@ -153,4 +187,4 @@ jobs:
       - name: Output success or failure
         id: output
         if: success() || failure()
-        run: if [[ ${{ steps.int-test-step.outcome }} != "success" ]]; then exit 1; else exit 0; fi
+        run: if [[ ${{ steps.int-test-step.outcome }} != "success" ]]; then echo 'Int tests failed!' && exit 1; else exit 0; fi
