add more ci steps to get screenshots back out, update allowed-scripts

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,15 +2,15 @@ name: Build and test package
 
 on:
   pull_request:
-    branches: [ main ]
+    branches: [main]
   push:
-    branches: [ main ]
+    branches: [main]
 
 env:
-  HOME_URL: 'http://localhost:3010/embedded/platform/'
-  REQUEST_URL: 'http://localhost:3010/embedded/platform/async/report/request-examples/request-example-success/request'
-  POLLING_URL: 'http://localhost:3010/embedded/platform/async/report/request-examples/request-example-success/request/exId_1729765628165'
-  REPORT_URL: 'http://localhost:3010/embedded/platform/async/report/request-examples/request-example-success/request/tblId_1729765628165/report'
+  HOME_URL: "http://localhost:3010/embedded/platform/"
+  REQUEST_URL: "http://localhost:3010/embedded/platform/async/report/request-examples/request-example-success/request"
+  POLLING_URL: "http://localhost:3010/embedded/platform/async/report/request-examples/request-example-success/request/exId_1729765628165"
+  REPORT_URL: "http://localhost:3010/embedded/platform/async/report/request-examples/request-example-success/request/tblId_1729765628165/report"
 
 jobs:
   build:
@@ -19,16 +19,16 @@ jobs:
       contents: read
 
     steps:
-    - uses: actions/checkout@v4
-    - uses: actions/setup-node@v4
-      with:
-        node-version: '24.x'
-    - run: npm run setup
-    - run: npm run rpack
-    - uses: actions/upload-artifact@v4
-      with:
-        name: dpr-package
-        path: dist
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: "24.x"
+      - run: npm run setup
+      - run: npm run rpack
+      - uses: actions/upload-artifact@v4
+        with:
+          name: dpr-package
+          path: dist
 
   test:
     runs-on: ubuntu-latest
@@ -40,7 +40,7 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
-          node-version: '24.x'
+          node-version: "24.x"
       - run: npm run setup
       - uses: actions/download-artifact@v4
         with:
@@ -68,7 +68,7 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
-          node-version: '22.x'
+          node-version: "22.x"
       - run: npm run setup
 
       - name: Clone mi-ui
@@ -104,7 +104,7 @@ jobs:
       - name: mi-ui integration tests
         run: npm run int-test
         working-directory: ${{ github.workspace }}/../app
-        
+
   integration_test:
     runs-on: ubuntu-latest
     needs: build
@@ -126,9 +126,37 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
-          node-version: '24.x'
+          node-version: "24.x"
       - run: npm run setup
       - run: npm run package
+      - name: count number of screenshots for visual regression tests before running
+        id: count-screenshots-before
+        run: echo -n "screenshots_before=$(find src/dpr/components/_dashboards/visual-regression-tests -name \*.png | wc -l | tr -d '[:space:]')" >> "$GITHUB_OUTPUT"
+
+      - name: Run the visual regression tests for dashboards
+        run: npm run int-test-visual
+
+      - name: count number of screenshots for visual regression tests after running
+        id: count-screenshots-after
+        run: |
+          echo "screenshots before: ${{ steps.count-screenshots-before.outputs.screenshots_before }}"
+          screenshots_after=$(find src/dpr/components/_dashboards/visual-regression-tests -name \*.png | wc -l | tr -d '[:space:]')
+          echo "screenshots after: $screenshots_after"
+          screenshot_diff=$((${{ steps.count-screenshots-before.outputs.screenshots_before }}-$screenshots_after))
+          if [ $screenshot_diff -eq 0 ]; then exit 0; else exit 1; fi
+      - name: Package up screenshots
+        if: success() || failure()
+        run: |
+          mkdir screenshots
+          find src/dpr/components/_dashboards/visual-regression-tests -name \*.png -exec cp {} screenshots \;
+
+      - uses: actions/upload-artifact@v4
+        name: Create screenshots artifact
+        if: success() || failure()
+        with:
+          name: screenshots
+          path: screenshots
+
       - name: Run the node app and integration tests
         id: int-test-step
         run: |
@@ -153,4 +181,4 @@ jobs:
       - name: Output success or failure
         id: output
         if: success() || failure()
-        run: if [[ ${{ steps.int-test-step.outcome }} != "success" ]]; then exit 1; else exit 0; fi
+        run: if [[ ${{ steps.int-test-step.outcome }} != "success" ]]; then echo 'Int tests failed!' && exit 1; elif [[ ${{ steps.count-screenshots-after.outcome }} != "success" ]]; then echo 'Visual regression test screenshots number changed - new tests likely added!' && exit 1; else exit 0; fi
